# conda env create -f environment-linux.yml
name: ctlearn-aswg19
channels:
    - anaconda
    - conda-forge
    - cta-observatory
    - menpo
dependencies:
    - python=3.6.5
    - matplotlib
    - numpy
    - astropy
    - opencv
    - pillow
    - pip
    # TensorFlow-CPU v1.12.0:
    - pip:
        - https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.12.0-cp36-cp36m-linux_x86_64.whl
    - pytables
    - vitables
    - pyyaml
    - scikit-learn
    - scipy
