# conda env create -f environment-macos.yml
name: ctlearn-aswg19
channels:
    - anaconda
    - conda-forge
    - cta-observatory
    - menpo
dependencies:
    - python=3.6.5
    - matplotlib
    - numpy
    - astropy
    - opencv
    - pillow
    - pip
    # TensorFlow-CPU v1.12.0:
    - pip:
        - https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.12.0-py3-none-any.whl
    - pytables
    - pyyaml
    - scikit-learn
    - scipy
