Data:
  Input:
    batch_size: 16
    map: true
    num_parallel_calls: 2
    prefetch: true
    prefetch_buffer_size: 1
    shuffle: true
    shuffle_buffer_size: 10000
  Loading:
    example_type: array
    merge_tel_types: True
    min_num_tels: 1
    seed: 1234
    selected_tel_types: ['MST:FlashCam']
    validation_split: 0.1
  Processing:
    sorting: size
  file_list: YOUR_PATH_TO/data/ctlearn/ctlearn_input.txt
  format: HDF5
Image Mapping:
  hex_conversion_algorithm:
    'LSTCam': 'oversampling'
    'FlashCam': 'oversampling'
    'NectarCam': 'oversampling'
    'SCTCam': 'oversampling'
    'DigiCam': 'oversampling'
    'ASTRICam': 'oversampling'
    'CHEC': 'oversampling'
  camera_types: ['FlashCam']
  interpolation_image_shape:
    'FlashCam':
        - 112
        - 112
        - 1
  padding:
    'LSTCam': 2
    'FlashCam': 1
    'NectarCam': 2
    'SCTCam': 4
    'DigiCam': 1
    'ASTRICam': 0
    'CHEC': 0
    'VERITAS': 1
Logging:
  model_directory: YOUR_PATH_TO/logs/
Model:
  Model Parameters:
    basic:
      conv_block:
        batchnorm: false
        bottleneck: null
        layers:
        - filters: 32
          kernel_size: 3
        - filters: 32
          kernel_size: 3
        - filters: 64
          kernel_size: 3
        - filters: 128
          kernel_size: 3
        max_pool:
          size: 2
          strides: 2
    cnn_rnn:
      cnn_block:
        function: conv_block
        module: basic
      dropout_rate: 0.5
      pretrained_weights: null
    single_tel:
      network:
        function: conv_block
        module: basic
      pretrained_weights: null
  model:
    function: cnn_rnn_model
    module: cnn_rnn
  model_directory: YOUR_PATH_TO/code/ctlearn/ctlearn/default_models/
Prediction:
  export_as_file: true
  prediction_file_path: YOUR_PATH_TO/logs/
  true_labels_given: true
TensorFlow:
  run_TFDBG: false
Training:
  Hyperparameters:
    adam_epsilon: 1.0e-08
    apply_class_weights: true
    base_learning_rate: 0.0001
    optimizer: Adam
    scale_learning_rate: false
    variables_to_train: null
  num_validations: 15
  num_training_steps_per_validation: 2500
